---
- hosts: webservers 
  become: True
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=no state=latest
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
         - restart apache2
    - name: install yum
      apt: name=yum update_cache=no state=latest

    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
        
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
...
